### ISSUE TITLE
 unknown variable query_cache_size

### ISSUE THREAD

**Issue by rudak** [alexanderkoller/low-memory-mysql#2]
mysql    | [Entrypoint] MySQL Docker Image 8.0.19-1.1.15
mysql    | 2020-02-15T18:18:30.982456Z 0 [ERROR] [MY-000067] [Server] unknown variable 'query_cache_size=0'.
mysql    | 2020-02-15T18:18:30.982651Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql    | [Entrypoint] ERROR: Unable to start MySQL. Please check your configuration.

;)

**Comment by axeII** [comment]
I had exactly same issue and the problem is that version 8.* doesn't support that parameter.
You can fix it by changing first line in _Dockerfile_ to: `FROM mysql/mysql-server:5.7`

If you are ok with mysql version 5.7 like me.
